[package]
name = "fen-ml"
version.workspace = true
edition.workspace = true

[[bin]]
name = "fen-baseline-worker"
path = "src/bin/worker.rs"

[features]
default = []
kafka = ["fen-events/kafka"]

[dependencies]
fen-core = { path = "../fen-core" }
fen-events = { path = "../fen-events" }

# CLI
clap.workspace = true

# Web
axum.workspace = true

# Utilities
uuid.workspace = true
chrono.workspace = true
rust_decimal.workspace = true
bincode.workspace = true

ort.workspace = true
ndarray.workspace = true
tokenizers.workspace = true
image.workspace = true

regex.workspace = true
once_cell.workspace = true
lru.workspace = true
rstar.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
async-trait.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
tokio-test.workspace = true

[lints]
workspace = true
