[package]
name = "fen-rules"
version.workspace = true
edition.workspace = true

[[bin]]
name = "fen-validation-worker"
path = "src/bin/worker.rs"

[features]
default = []
kafka = ["fen-events/kafka"]

[dependencies]
fen-core = { path = "../fen-core" }
fen-events = { path = "../fen-events" }
fen-storage = { path = "../fen-storage" }
fen-notify = { path = "../fen-notify" }

# CLI
clap.workspace = true

# Web
axum.workspace = true

# Utilities
uuid.workspace = true

zen-engine.workspace = true
serde.workspace = true
serde_json.workspace = true
bincode.workspace = true
base64 = "0.22"
thiserror.workspace = true
async-trait.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
rust_decimal.workspace = true

chrono.workspace = true

[lints]
workspace = true
