[package]
name = "fen-graph"
version.workspace = true
edition.workspace = true

[dependencies]
fen-core = { path = "../fen-core" }
kyu-graph = { path = "../../../kyugraph/crates/kyu-graph" }
kyu-delta = { path = "../../../kyugraph/crates/kyu-delta" }
ext-rdf = { path = "../../../kyugraph/extensions/ext-rdf" }
smol_str = "0.3"
async-trait.workspace = true
tokio.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
chrono.workspace = true
rust_decimal.workspace = true
thiserror.workspace = true

[dev-dependencies]
rust_decimal_macros.workspace = true

[lints]
workspace = true
