# Keycloak Terraform Outputs

output "realm_id" {
  description = "The ID of the Fen realm"
  value       = keycloak_realm.fen.id
}

output "realm_name" {
  description = "The name of the Fen realm"
  value       = keycloak_realm.fen.realm
}

output "oidc_issuer_url" {
  description = "OIDC issuer URL for the Fen realm"
  value       = "${var.keycloak_url}/realms/${keycloak_realm.fen.realm}"
}

output "oidc_authorization_endpoint" {
  description = "OIDC authorization endpoint"
  value       = "${var.keycloak_url}/realms/${keycloak_realm.fen.realm}/protocol/openid-connect/auth"
}

output "oidc_token_endpoint" {
  description = "OIDC token endpoint"
  value       = "${var.keycloak_url}/realms/${keycloak_realm.fen.realm}/protocol/openid-connect/token"
}

output "oidc_userinfo_endpoint" {
  description = "OIDC userinfo endpoint"
  value       = "${var.keycloak_url}/realms/${keycloak_realm.fen.realm}/protocol/openid-connect/userinfo"
}

output "oidc_logout_endpoint" {
  description = "OIDC end session endpoint"
  value       = "${var.keycloak_url}/realms/${keycloak_realm.fen.realm}/protocol/openid-connect/logout"
}

output "oidc_jwks_uri" {
  description = "OIDC JWKS URI for token validation"
  value       = "${var.keycloak_url}/realms/${keycloak_realm.fen.realm}/protocol/openid-connect/certs"
}

output "api_client_id" {
  description = "Client ID for the API client"
  value       = keycloak_openid_client.fen_api.client_id
}

output "web_client_id" {
  description = "Client ID for the web client"
  value       = keycloak_openid_client.fen_web.client_id
}

output "roles" {
  description = "Available realm roles"
  value = {
    system_admin = keycloak_role.system_admin.name
    tenant_admin = keycloak_role.tenant_admin.name
    analyst      = keycloak_role.analyst.name
    viewer       = keycloak_role.viewer.name
    rule_manager = keycloak_role.rule_manager.name
  }
}

output "env_file_content" {
  description = "Environment variables for fen-api configuration"
  sensitive   = true
  value       = <<-EOT
    # Generated by Terraform - Keycloak configuration for fen-api
    OIDC_ISSUER_URL=${var.keycloak_url}/realms/${keycloak_realm.fen.realm}
    OIDC_CLIENT_ID=${keycloak_openid_client.fen_api.client_id}
    OIDC_CLIENT_SECRET=${var.fen_api_client_secret}
    OIDC_REDIRECT_URI=http://localhost:3000/auth/callback
    OIDC_SCOPES=openid,profile,email
  EOT
}
